name: main
on:
  push:
    branches:
      - main

jobs:

  build-and-publish-snap:
    name: Build and publish dive snap
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: install snapcraft
        run: |
          sudo snap install snapcraft --classic
      - name: build
        run: |
          snapcraft --destructive-mode
        id: build
      - name: publish snap
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run:
          snapcraft upload --release=edge ./dive_0.10.0_amd64.snap
